server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://47.98.169.233:3306/fashion?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: Jerry@1234
